name: browser_storage
description: Allows manipulation of Storage on Web platform while using an in-memory map for other platforms. Based on https://github.com/JCQuintas/session_storage. 
version: 0.0.2
homepage: https://github.com/owlxcorp/browser_storage

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^0.5.0

dev_dependencies:
  dart_code_metrics: ^5.4.0
  flutter_test:
    sdk: flutter
